name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:

  push-all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        docker login -u ${USERNAME} -p "${DOCKER_REGISTRY_TOKEN}"
        make push-base push-tasks
      env:
        DOCKER_REGISTRY_TOKEN: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
        USERNAME: maxbischoff
        DOCKER_REPO: maxbischoff
